apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "prometheus-new-relic-app-exporter.fullname" . }}
  labels:
{{ include "prometheus-new-relic-app-exporter.labels" . | indent 4 }}
data:
  new_relic_api_key: {{ .Values.new_relic_api_key | b64enc | quote }}
