{{- if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-new-relic-app-exporter.fullname" . }}
  labels:
{{ include "prometheus-new-relic-app-exporter.labels" . | indent 4 }}
  annotations:
{{- toYaml .Values.service.annotations | nindent 8 }}
spec:
  ports:
    - port: 80
      targetPort: 9000
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "prometheus-new-relic-app-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
